Repository wso2/carbon-apimgt, pull requests merged in 2019-04, with the labels that each got.

#6078 Improvements to the API Listing page
  features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/public/theme/defaultTheme.js
  features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ApiTableView.jsx
  features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ApiThumb.jsx
  features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/ImageGenerator.jsx
  features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/Listing.jsx
  features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/source/src/app/components/Apis/Listing/StarRating.jsx
Labels: APIM 3.0.0, Docs/Has Impact

#6079 Add labeling feature to cloud hybrid gateway
  components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/api/synchronizer/APISynchronizer.java
  components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/api/synchronizer/dto/LabelDTO.java
  components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.api.synchronizer/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/api/synchronizer/util/APISynchronizationConstants.java
  components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.common/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/common/util/OnPremiseGatewayConstants.java
  components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.configurator/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/configurator/ConfigConstants.java
  components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.configurator/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/configurator/Configurator.java
  components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.configurator/src/main/java/org/wso2/carbon/apimgt/hybrid/gateway/configurator/dto/MicroGatewayInitializationDTO.java
  components/apimgt/org.wso2.carbon.apimgt.hybrid.gateway/org.wso2.carbon.apimgt.hybrid.gateway.configurator/src/test/java/org/wso2/carbon/apimgt/hybrid/gateway/configurator/ConfiguratorTest.java
Labels: APIM 2.7.0, Docs/No Impact

#6121 Fix rest api doc generation
  features/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.feature/pom.xml
  features/apimgt/org.wso2.carbon.apimgt.rest.api.store.feature/pom.xml
Labels: Docs/No Impact

#6019 Add configuration to provide blocking condition retriever service URL
  components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
  features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
Labels: Docs/Has Impact

#6177 Token Revocation Feature
  components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIConstants.java
  components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIManagerConfiguration.java
  components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/events/APIMOAuthEventInterceptor.java
  components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/events/TokenRevocationNotifierImpl.java
  components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/internal/APIKeyMgtServiceComponent.java
  components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/internal/ServiceReferenceHolder.java
  components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/TokenRevocationNotifier.java
  components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/events/APIMOAuthEventInterceptorTest.java
  components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/java/org/wso2/carbon/apimgt/keymgt/events/TokenRevocationNotifierImplTest.java
  components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/resources/security/client-truststore.jks
  components/apimgt/org.wso2.carbon.apimgt.keymgt/src/test/resources/security/wso2carbon.jks
  features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/config/api-manager.xml
  features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventpublishers/tokenRevokeEventJMSPublisher.xml
  features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventreceivers/tokenRevocationWso2EventReceiver.xml
  features/apimgt/org.wso2.carbon.apimgt.throttling.siddhi.extension.feature/src/main/resources/conf/eventstreams/org.wso2.apimgt.token.revocation.stream_1.0.0.json
Labels: Docs/Has Impact
